# Generated by Django 3.2.18 on 2023-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_teacher',
            field=models.CharField(default='', max_length=50),
        ),
    ]
