# Generated by Django 3.2.18 on 2023-02-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230228_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
