# Generated by Django 3.2.18 on 2023-02-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
