# Generated by Django 3.2.18 on 2023-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentlist_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='user_role',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
