# Generated by Django 3.2.18 on 2023-03-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='at_date',
        ),
    ]
