# Generated by Django 3.2.18 on 2023-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_attendance_at_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('at_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
